language: node_js
node_js:
  - "4.2.6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env: CXX=g++-4.8
before_script:
  - sudo apt-get -qq install libnotify-bin
  - npm install -g gulp
script: gulp